### PR TITLE
try fixing RSS feed

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
Sorry for meddling!

https://deploy-preview-17--researchsoft.netlify.app/feed.xml

It uses Hugo built-in RSS template, that can be tweaked by adding a template. It could be stored in the layouts/ folder (or in a themes/themename/layouts folder -- note that with Hugo you can combine several themes so no edit of the syna theme is necessary). rOpenSci default RSS template: https://github.com/ropensci/roweb3/blob/main/themes/ropensci/layouts/_default/rss.xml and the one created for a special aggregator: https://github.com/ropensci/roweb3/blob/main/themes/ropensci/layouts/rbloggers/rss.xml

@mfenner

**Comment by mfenner** [comment]
Thank you @maelle !

**Comment by mdbarker** [comment]
Hi Martin, should I go ahead and merge this PR?
I am not an RSE so only have the most basic understanding of our website and these issues!

Cheers
Michelle

________________________________

**Comment by mfenner** [comment]
@mdbarker I had asked @maelle to help with this bug, she knows much more about Hugo than I do. She has done a lot of work for rOpenSci, including their website. So it would be great if you could merge this PR.

**Comment by mdbarker** [comment]
Yes, thanks @maelle<https://github.com/maelle>

I think I have merged the PR but let me know if there's more I need to do, as GitHub is not my expertise.

Cheers
Michelle

________________________________

**Pull request merged**
